import re

with open("app.py", "r") as f:
    content = f.read()

imports = """
from fastapi.responses import FileResponse, JSONResponse, ORJSONResponse
import smtplib
from email.message import EmailMessage
import base64
from pydantic import BaseModel
from typing import Optional
"""
content = content.replace("from fastapi.responses import FileResponse, JSONResponse, ORJSONResponse", imports.strip())

endpoint = """

class EmailShareRequest(BaseModel):
    recipient: str
    prompt: str
    owner: str
    graphBase64: Optional[str] = None

@app.post("/api/email/share")
async def share_email(req: EmailShareRequest):
    try:
        query = {}
        if req.owner and req.owner != "All":
            query["AssignedTo"] = req.owner
            
        cursor = issues_collection.find(query, {"_id": 0})
        data = list(cursor)
        
        if not data:
            return JSONResponse({"error": f"No vulnerabilities found for owner: {req.owner}"}, status_code=404)
        
        df = pd.DataFrame(data)
        excel_buffer = BytesIO()
        df.to_excel(excel_buffer, index=False, engine='openpyxl')
        excel_buffer.seek(0)
        
        msg = EmailMessage()
        msg['Subject'] = f"Security Vulnerability Report - {req.owner if req.owner != 'All' else 'All Owners'}"
        msg['From'] = os.environ.get("SMTP_USER", "security-portal@xtelify.com")
        msg['To'] = req.recipient
        msg.set_content(f"Hello,\\n\\nPlease find the requested Security Vulnerability Report attached.\\n\\nInstructions/Notes:\\n{req.prompt}\\n\\nGenerated by Xtelify Security Portal.")
        
        msg.add_attachment(
            excel_buffer.read(),
            maintype='application',
            subtype='vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            filename=f"vulnerabilities_{req.owner.replace(' ', '_')}.xlsx"
        )
        
        if req.graphBase64:
            try:
                b64_data = req.graphBase64
                if "," in b64_data:
                    b64_data = b64_data.split(",")[1]
                image_data = base64.b64decode(b64_data)
                msg.add_attachment(
                    image_data,
                    maintype='image',
                    subtype='png',
                    filename="vulnerability_graph.png"
                )
            except Exception as e:
                print(f"Failed to attach graph image: {e}")
                
        smtp_host = os.environ.get("SMTP_HOST")
        smtp_port = os.environ.get("SMTP_PORT", 587)
        smtp_user = os.environ.get("SMTP_USER")
        smtp_pass = os.environ.get("SMTP_PASS")
        
        if smtp_host and smtp_user and smtp_pass:
            with smtplib.SMTP(smtp_host, int(smtp_port)) as server:
                server.starttls()
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)
            print(f"Email sent successfully to {req.recipient}")
        else:
            print("SMTP credentials not found. Simulating email send.")
            print(f"--- EMAIL SIMULATION ---")
            print(f"To: {req.recipient}")
            print(f"Subject: {msg['Subject']}")
            print(f"Body: {msg.get_content()}")
            print(f"Attachments: vulnerabilities_{req.owner.replace(' ', '_')}.xlsx")
            if req.graphBase64:
                print(f"             vulnerability_graph.png")
            print(f"------------------------")

        return JSONResponse({"status": "success", "message": "Email sent successfully"})
        
    except Exception as e:
        import traceback
        err = traceback.format_exc()
        print(f"Error in share_email:\\n{err}")
        return JSONResponse({"error": str(e)}, status_code=500)
"""

content += endpoint

with open("app.py", "w") as f:
    f.write(content)
